version: '3'

services:
  code_educator:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
      - DEV_MODE=docker
    tty: true
    stdin_open: true
    networks:
      - code_educator_network

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"  # Ollama API port
    networks:
      - code_educator_network

networks:
  code_educator_network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
  # Ollama data volume to persist model data
